ASoC: Fix missed replacement DMA_COMPLETE->EDMA_COMPLETE
Fixes the following introduced by ('dmanengine: fix edma driver to not
define DMA_COMPLETE'):

  CC [M]  sound/soc/davinci/davinci-pcm.o
sound/soc/davinci/davinci-pcm.c: In function ‘davinci_pcm_dma_irq’:
sound/soc/davinci/davinci-pcm.c:241: error: ‘DMA_COMPLETE’ undeclared (first use in this function)
sound/soc/davinci/davinci-pcm.c:241: error: (Each undeclared identifier is reported only once
sound/soc/davinci/davinci-pcm.c:241: error: for each function it appears in.)

Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
Signed-off-by: Olof Johansson <olof@lixom.net>